---
title: "Presentation Title"
subtitle: "DSAN 5900"
author: "enter your name here"
date: last-modified
format:
  html:
    page-layout: full
    code-fold: show
    code-copy: true
    code-tools: true
    code-overflow: wrap
    self-contained: true
    embed-resources: true
---

## Introduction

```{r}
library(naniar)
library(visdat)
library(reticulate)
library(plotly)
library(dplyr)
library(ggplot2)
library(tidyverse)

df_clean <- read.csv("cleanedAdmissions.csv")
```



## Viz 1

```{r}
ggplot(df_clean, aes(x = GPA)) +
  geom_histogram(binwidth = 0.1, fill = "skyblue", color = "darkgray") +
  labs(title = "Histogram of GPA Scores", x = "GPA", y = "Frequency") +
  theme_minimal() 
```


## Viz 2

```{r}
ggplot(df_clean, aes(x = WorkExp, y = GPA, color = Decision)) +
  geom_point(shape = 4, alpha = 0.6) +
  scale_color_manual(values = c("Admit" = "green", "Decline" = "red", "Waitlist" = "orange")) +
  labs(title = "Scatter Plot of Work Experience vs. GPA",
       x = "Work Experience (Years)", y = "GPA") +
  theme_minimal(base_size = 13.5) +
  theme(legend.background = element_rect(fill = "mintcream", size = 0.5, linetype = "solid"),
        legend.key = element_blank(),
        legend.box.background = element_rect(color = "black"))

```



## Viz 3

```{r}
ggplot(df_clean, aes(x = State, y = WritingScore, fill = State)) +
  geom_bar(stat = "summary", fun = "mean") +
  labs(title = "Average Writing Score by State", x = "State", y = "Average Writing Score") +
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```




## Conclusion







